### ISSUE TITLE
Suggestion: github.com/r-lib

### ISSUE THREAD

**Issue by knbknb** [kbroman/hipsteR#9]
The https://github.com/r-lib/ repo seems to aggregate a lot of r packages. Seems to me that -at this time- there is no mention of it in your tutorial (not in the huma-readable text)  I don't know how "official" this repo is, or how important. Maybe you could clarify this in your tutorial?

**Comment by kbroman** [comment]
Thanks for the suggestion. I've added to the section on Hadley's packages, which probably should just be re-titled Tidyverse. I'm thinking tidyverse.org is probably a better pointer than github.com/r-lib.
